// lessons.js — "Learn something in 30 seconds." A curated, static pool of
// bite-sized wine lessons. V1 is deliberately lightweight: no AI, no scheduling,
// no admin — one lesson surfaces per calendar day, rotating deterministically so
// every user sees the same one. Each lesson is a tiny moment of competence:
// an irresistible question, a clear answer, three things you now know.
const LESSONS = [
  { title:'Why Champagne has bubbles',
    body:`A second fermentation happens inside the sealed bottle, and the carbon dioxide has nowhere to go. Pop the cork and that trapped pressure rushes out as bubbles.`,
    chips:['Second ferment','Sealed in','Pressure'] },
  { title:'Why Pinot Noir costs more',
    body:`The grape is thin-skinned, fussy, and rots in the rain, so it's grown carefully in cool places and gives small yields. Difficulty shows up in the price.`,
    chips:['Thin-skinned','Hard to grow','Cool-climate'] },
  { title:`Chablis isn't a grape`,
    body:`It's a place in northern France, and the wine is 100% Chardonnay — just lean, crisp, and minerally instead of rich and buttery. Same grape, cooler accent.`,
    chips:['A place','Chardonnay','Mineral'] },
  { title:'Why people love Barolo',
    body:`Made from Nebbiolo in Piedmont, it smells of roses and tar and ages for decades. Time softens its firm grip into something silky and complex.`,
    chips:['Nebbiolo','Rose & tar','Ages well'] },
  { title:`What "dry" actually means`,
    body:`Simply: not sweet. The grape sugar fermented into alcohol. A dry wine can still smell of ripe peach or berry and trick you into thinking it's sweet.`,
    chips:['Not sweet','Fruity ≠ sweet','Most wine'] },
  { title:'Burgundy vs Bordeaux',
    body:`Burgundy is usually a single grape — Pinot Noir or Chardonnay. Bordeaux is a blend, mostly Cabernet and Merlot. One leans delicate, the other structured.`,
    chips:['Burgundy = 1 grape','Bordeaux = blend','Both French'] },
  { title:'Why one rosé is $12 and another is $40',
    body:`Cheap rosé is often a by-product of making red. The pricier ones — think Provence — are made on purpose from the first day. Intention costs money.`,
    chips:['Made on purpose','Provence','Pale & dry'] },
  { title:'Why some wines taste oaky',
    body:`Aging in oak barrels adds vanilla, toast, and baking spice. New barrels cost hundreds of dollars each, which is one more reason oaky wines cost more.`,
    chips:['Oak barrels','Vanilla & toast','Adds cost'] },
  { title:'What tannin is',
    body:`That dry, grippy feeling on your gums in big reds — like over-steeped tea. It comes from grape skins and seeds, and it softens with food and age.`,
    chips:['Grip','From skins','Softens with food'] },
  { title:'Why red wine is red',
    body:`Color comes from soaking the juice on dark grape skins. White wine skips that step — which is why you can make a white wine from red grapes.`,
    chips:['Skin contact','Gives color','And tannin'] },
  { title:'Old World vs New World',
    body:`"Old World" (Europe) tends to taste earthy and restrained; "New World" (everywhere else) tends to taste riper and bolder. Same grape, different accent.`,
    chips:['Europe = earthy','New World = ripe','A style'] },
  { title:'Why Sancerre is so loved',
    body:`It's Sauvignon Blanc from the Loire Valley — all grapefruit, fresh-cut grass, and a flinty snap. It's the crisp, refreshing white people chase in summer.`,
    chips:['Sauvignon Blanc','Grapefruit','Flinty'] },
  { title:'Why Champagne only comes from Champagne',
    body:`By law, only sparkling wine from that one French region may use the name. Bubbles made elsewhere go by sparkling, Cava, Prosecco, or Crémant.`,
    chips:['Protected name','One region','Else = sparkling'] },
  { title:'Prosecco vs Champagne',
    body:`Prosecco gets its fizz in a big tank — fast, fruity, affordable. Champagne gets it slowly, bottle by bottle — toasty, complex, pricier. Different methods.`,
    chips:['Tank vs bottle','Fruity vs toasty','Price'] },
  { title:'Why Malbec means Argentina',
    body:`It's a French grape that found its true home in sunny Mendoza, high in the Andes, where it turns plush, dark, and smooth — a natural partner for steak.`,
    chips:['French grape','Mendoza','Plush'] },
  { title:'Why Riesling gets a bad rap',
    body:`People assume it's always sweet, but most Riesling is bone-dry and electric with acidity. If you want the dry style, look for "trocken" on the label.`,
    chips:['Often dry','"Trocken"','High acid'] },
  { title:`What "vintage" means`,
    body:`Just the year the grapes were picked. Weather changes every year, so the same wine can taste different vintage to vintage. "NV" means a blend of years.`,
    chips:['Harvest year','Weather matters','NV = blend'] },
  { title:'Why you swirl wine',
    body:`Swirling coats the glass and feeds the wine air, which releases its aromas. Since most of what we call taste is actually smell, swirling makes wine taste better.`,
    chips:['Adds air','Frees aroma','Smell = taste'] },
  { title:'Why Beaujolais loves a chill',
    body:`It's light, juicy Gamay with low tannin. Fifteen minutes in the fridge makes it bright and refreshing — the rare red that's perfect on a warm day.`,
    chips:['Gamay','Serve cool','Crowd-pleaser'] },
  { title:`What makes a wine "natural"`,
    body:`It's made with as little added as possible — wild yeast, no fining or filtering, little or no added sulfur. The result is often cloudy, lively, and a bit wild.`,
    chips:['Few additives','Cloudy','Lively'] },
  { title:'Why Napa Cabernet is pricey',
    body:`Famous vineyard land, intense demand, and lots of new oak. Cabernet Sauvignon from Napa Valley is California's status red — ripe, powerful, and built to impress.`,
    chips:['Famous land','High demand','Bold'] },
  { title:'Why orange wine is orange',
    body:`It's white grapes made like a red — the juice left to soak on the skins. That contact gives amber color, a grippy texture, and a savory, almost nutty edge.`,
    chips:['Skin contact','Amber','Savory'] },
  { title:'The trick to ordering wine out',
    body:`Name two wines you've enjoyed and your budget. Any good server takes it from there. You don't need vocabulary — you just need to know what you've liked.`,
    chips:['Give examples','Give a price','Relax'] },
  { title:'Why serving temperature matters',
    body:`A red served too warm tastes boozy and flat; a white served ice-cold tastes like nothing. Fifteen minutes in or out of the fridge fixes both.`,
    chips:['Cool the red','Warm the white','15 minutes'] },
  { title:'Why Chianti needs food',
    body:`Tuscany's Sangiovese is high in acid and savory tannin — almost too much on its own. With tomato, olive oil, and parmesan, it suddenly makes perfect sense.`,
    chips:['Sangiovese','High acid','Loves food'] },
  { title:'Why sommeliers love Grüner Veltliner',
    body:`Austria's crisp white has a signature white-pepper snap and pairs with foods that defeat most wine, like asparagus and artichokes. A secret-weapon bottle.`,
    chips:['Austria','White pepper','Versatile'] },
  { title:'Why Port is sweet',
    body:`Fermentation is stopped early with a splash of grape spirit, leaving natural sweetness and a higher kick of alcohol. It's why a little goes a long way.`,
    chips:['Fortified','Stopped early','After dinner'] },
  { title:`What "minerality" means`,
    body:`That wet-stone, oyster-shell freshness you find in crisp whites like Chablis and Muscadet. It's hard to define and strangely easy to crave.`,
    chips:['Wet stone','Saline','In crisp whites'] },
  { title:'Why Bordeaux ages so well',
    body:`Its firm tannin and bright acidity act like preservatives. Over years they slowly soften, trading youthful grip for a smoother, more complex wine.`,
    chips:['Tannin','Acidity','Time'] },
  { title:'Why Sauternes costs a fortune',
    body:`A "noble rot" shrivels the grapes on the vine, concentrating their sugar. The yields are tiny and the picking is painstaking — the reward is liquid gold.`,
    chips:['Noble rot','Tiny yields','Dessert'] },
  { title:'Vinho Verde, the $10 hero',
    body:`Portugal's young, faintly fizzy white is light, low in alcohol, and bracingly fresh. It's built for hot afternoons and barely dents your wallet.`,
    chips:['Portugal','Light & fizzy','Great value'] },
  { title:'Why decanting helps',
    body:`Pouring wine into a carafe gives it air and leaves any sediment behind. It wakes up a young, tight red in minutes — and a big glass does almost the same.`,
    chips:['Adds air','Drops sediment','Young reds'] },
];

// One lesson per UTC day, rotating through the whole pool. Deterministic and
// shared across users — no storage, no scheduling. Returns today's lesson, the
// next one (for a "tomorrow" teaser), and the index.
function lessonForToday(){
  const day = Math.floor(Date.now() / 86400000);
  const i = ((day % LESSONS.length) + LESSONS.length) % LESSONS.length;
  return { lesson: LESSONS[i], next: LESSONS[(i + 1) % LESSONS.length], index: i };
}

export { LESSONS, lessonForToday };
