// regions.js — curated Explore region library (first wave, ~22 regions).
// Each region: { country, grapes[], keys[] (search aliases + own-from-here match),
//   taste, pairs[], prompts[3] (region-specific sommelier conversation starters) }.
// FEATURED = the default pills shown when the search box is empty.

export const FEATURED = ['Beaujolais','Burgundy','Loire','Piedmont','Tuscany','Napa Valley','Oregon','Mendoza'];

export const REGIONS = {
  // ── France ──────────────────────────────────────────────────────────
  'Beaujolais':{ country:'France', grapes:['Gamay'], keys:['beaujolais','morgon','fleurie','brouilly'],
    taste:'Granite hills just south of Burgundy. Gamay here is juicy, floral and low-tannin — joyful, chillable reds that go with almost anything.',
    pairs:['Charcuterie','Roast chicken','Picnic spreads','Thanksgiving dinner'],
    prompts:['Is Gamay the only grape grown in Beaujolais?','What is a Cru Beaujolais?','What should I buy next if I like Beaujolais?'] },
  'Burgundy': { country:'France', grapes:['Pinot Noir','Chardonnay'], keys:['burgundy','bourgogne','côte'],
    taste:'The world’s benchmark for Pinot Noir and Chardonnay. Precise, earthy, and age-worthy — wines that trade power for detail and a sense of place.',
    pairs:['Roast chicken','Mushrooms','Soft cheese','Salmon'],
    prompts:['Why is Burgundy so expensive?','What’s the difference between a Village and a Premier Cru?','Where should I look for affordable Burgundy?'] },
  'Chablis':  { country:'France', grapes:['Chardonnay'], keys:['chablis'],
    taste:'Burgundy’s coolest, northernmost outpost. Chardonnay here is bone-dry, steely and mineral — green apple and crushed-shell, with little or no oak. Precision in a glass.',
    pairs:['Oysters','Shellfish','Goat cheese','Sushi'],
    prompts:['What makes Chablis taste so different from other Chardonnay?','What is Kimmeridgian soil?','What should I buy if I like Chablis?'] },
  'Champagne':{ country:'France', grapes:['Chardonnay','Pinot Noir','Pinot Meunier'], keys:['champagne'],
    taste:'The benchmark for sparkling wine, from chalky soils northeast of Paris. Bracing acidity, fine bubbles, and flavours of green apple, brioche and toasted nuts.',
    pairs:['Oysters','Fried foods','Soft cheese','Celebrations'],
    prompts:['What does “Brut” actually mean?','What is Blanc de Blancs?','Is grower Champagne worth seeking out?'] },
  'Loire':    { country:'France', grapes:['Chenin Blanc','Sauvignon Blanc','Cabernet Franc','Melon de Bourgogne'], keys:['loire','montlouis','vouvray','sancerre','muscadet'],
    taste:'A long, cool river valley making some of France’s most refreshing wines — crisp, mineral whites (Chenin, Sauvignon) and bright, leafy reds (Cabernet Franc).',
    pairs:['Goat cheese','Shellfish','Pork','Fresh salads'],
    prompts:['What grapes is the Loire known for?','What exactly is Sancerre?','What’s a good Loire wine for oysters?'] },
  'Rhône':    { country:'France', grapes:['Syrah','Grenache','Mourvèdre','Viognier'], keys:['rhone','rhône','châteauneuf','chateauneuf','hermitage','côte-rôtie','gigondas'],
    taste:'A sun-warmed valley in two halves: peppery, smoky Syrah in the north; generous Grenache-led blends in the south (Châteauneuf-du-Pape). Warm, savoury, herb-and-spice reds.',
    pairs:['Grilled meats','Lamb','Stews','Hard cheese'],
    prompts:['What’s the difference between Northern and Southern Rhône?','What grapes go into Châteauneuf-du-Pape?','What should I buy if I like Syrah?'] },
  'Bordeaux': { country:'France', grapes:['Cabernet Sauvignon','Merlot','Cabernet Franc'], keys:['bordeaux','médoc','medoc','margaux','pomerol','saint-émilion','st-émilion'],
    taste:'The world’s most famous red region. The Left Bank is Cabernet-driven and structured; the Right Bank is plush and Merlot-led. Cassis, cedar, tobacco and firm, age-worthy tannin.',
    pairs:['Steak','Lamb','Roast beef','Aged cheese'],
    prompts:['What’s the difference between Left Bank and Right Bank?','Why is Bordeaux usually a blend?','How do I find good affordable Bordeaux?'] },
  'Alsace':   { country:'France', grapes:['Riesling','Gewürztraminer','Pinot Gris'], keys:['alsace'],
    taste:'A sunny, German-influenced corner of eastern France. Aromatic, mostly dry whites — racy Riesling, exotic Gewürztraminer — with purity, perfume and a floral lift.',
    pairs:['Spicy food','Pork','Charcuterie','Onion tart'],
    prompts:['Is Alsace Riesling sweet or dry?','What is Gewürztraminer like?','What pairs well with Alsace whites?'] },

  // ── Italy ───────────────────────────────────────────────────────────
  'Piedmont': { country:'Italy', grapes:['Nebbiolo','Barbera','Dolcetto'], keys:['piedmont','piemonte','barolo','barbaresco'],
    taste:'Foggy hills in Italy’s northwest. Nebbiolo (Barolo, Barbaresco) is pale but powerful — tar, roses, and firm tannin that rewards patience.',
    pairs:['Braised beef','Mushroom risotto','Truffle dishes','Aged cheese'],
    prompts:['What’s the difference between Barolo and Barbaresco?','Why does Nebbiolo need aging?','What should I buy if I like Piedmont reds?'] },
  'Tuscany':  { country:'Italy', grapes:['Sangiovese'], keys:['tuscany','toscana','chianti','montepulciano','brunello'],
    taste:'Sun-baked hills of central Italy. Sangiovese gives tart-cherry fruit, dried herbs, and a savory, mouth-watering grip — built for the table (Chianti, Brunello).',
    pairs:['Pizza','Pasta with red sauce','Cured meats','Grilled vegetables'],
    prompts:['What’s the difference between Chianti and Brunello?','What is a Super Tuscan?','What food pairs best with Sangiovese?'] },
  'Veneto':   { country:'Italy', grapes:['Corvina','Glera','Garganega'], keys:['veneto','valpolicella','amarone','soave','prosecco'],
    taste:'Italy’s prolific northeast — fizzy Prosecco, crisp Soave whites, and rich, raisined Amarone made from dried Corvina grapes. The range runs from breezy to brooding.',
    pairs:['Antipasti','Risotto','Braised meats','Hard cheese'],
    prompts:['What is Amarone and why is it special?','Is all Prosecco sweet?','What should I buy if I like Italian reds?'] },
  'Sicily':   { country:'Italy', grapes:['Nero d’Avola','Grillo','Frappato'], keys:['sicily','sicilia'],
    taste:'A sun-baked Mediterranean island making bold, juicy reds from Nero d’Avola and fresh, saline whites from Grillo. Generous fruit with a wild, herbal edge.',
    pairs:['Grilled fish','Pasta','Eggplant','Cured meats'],
    prompts:['What is Nero d’Avola like?','What white wines does Sicily make?','What should I try from Sicily?'] },
  'Etna':     { country:'Italy', grapes:['Nerello Mascalese','Carricante'], keys:['etna'],
    taste:'Volcanic vineyards on the slopes of Mount Etna. Nerello Mascalese gives pale, high-acid, almost Burgundian reds — ash, red cherry and smoke — grown on black volcanic soils.',
    pairs:['Roast chicken','Mushrooms','Grilled fish','Tomato pasta'],
    prompts:['Why is Etna compared to Burgundy?','What does volcanic soil do to wine?','What should I buy if I like Nerello Mascalese?'] },

  // ── United States ───────────────────────────────────────────────────
  'Napa Valley':{ country:'USA', grapes:['Cabernet Sauvignon','Chardonnay','Merlot'], keys:['napa','oakville','rutherford','stags leap'],
    taste:'California’s most famous valley. Warm days and cool nights give rich, ripe Cabernet Sauvignon — bold black fruit, polished tannin, and generous oak.',
    pairs:['Ribeye','Lamb','Burgers','Aged hard cheese'],
    prompts:['Why is Napa Cabernet so prized?','What’s the difference between Napa and Sonoma?','What should I buy if I like Napa Cabernet?'] },
  'Sonoma':   { country:'USA', grapes:['Pinot Noir','Chardonnay','Zinfandel'], keys:['sonoma','russian river','dry creek'],
    taste:'Napa’s cooler, more laid-back neighbour. Coastal fog brings elegant Pinot Noir and Chardonnay (Russian River) plus old-vine Zinfandel — a little fresher and more varied than Napa.',
    pairs:['Salmon','Roast chicken','Pork','Mushrooms'],
    prompts:['What’s the difference between Napa and Sonoma?','What is Russian River Valley known for?','What should I buy if I like Sonoma Pinot?'] },
  'Oregon':   { country:'USA', grapes:['Pinot Noir','Chardonnay','Pinot Gris'], keys:['oregon'],
    taste:'Cool, rainy and green — Oregon makes high-acid Pinot Noir full of red-cherry fruit, freshness, and an earthy, forest-floor edge. Think elegance over power.',
    pairs:['Roast chicken','Salmon','Mushroom dishes','Duck'],
    prompts:['Why is Oregon known for Pinot Noir?','What is the Willamette Valley?','How does Oregon Pinot differ from Burgundy?'] },
  'Willamette Valley':{ country:'USA', grapes:['Pinot Noir','Chardonnay','Pinot Gris'], keys:['willamette'],
    taste:'Oregon’s cool, green heart and one of the world’s great Pinot Noir zones. Red-cherry fruit, bright acidity and an earthy, forest-floor depth — elegance over power.',
    pairs:['Salmon','Duck','Mushrooms','Roast chicken'],
    prompts:['Why is the Willamette Valley so good for Pinot Noir?','How does it compare to Burgundy?','What should I buy if I like Oregon Pinot?'] },
  'Santa Barbara':{ country:'USA', grapes:['Pinot Noir','Chardonnay','Syrah'], keys:['santa barbara','sta. rita','santa rita','sta rita','santa ynez'],
    taste:'Central-coast California where east–west valleys funnel cool ocean air inland. Bright Pinot Noir and Chardonnay (Sta. Rita Hills) plus peppery, cool-climate Syrah.',
    pairs:['Grilled fish','Roast chicken','Pork','Mushrooms'],
    prompts:['What is Sta. Rita Hills known for?','Why is Santa Barbara good for Pinot Noir?','What should I buy from Santa Barbara?'] },

  // ── Spain ───────────────────────────────────────────────────────────
  'Rioja':    { country:'Spain', grapes:['Tempranillo','Garnacha'], keys:['rioja'],
    taste:'Spain’s classic red region. Tempranillo aged in American oak gives savoury red fruit, leather, dill and vanilla. Crianza, Reserva and Gran Reserva mark increasing age.',
    pairs:['Lamb','Grilled meats','Cured meats','Hard cheese'],
    prompts:['What do Crianza, Reserva and Gran Reserva mean?','What grape is Rioja made from?','What should I buy if I like Rioja?'] },
  'Ribera del Duero':{ country:'Spain', grapes:['Tempranillo'], keys:['ribera','duero'],
    taste:'A high, harsh plateau north of Madrid making powerful Tempranillo (here called Tinto Fino). Darker, denser and more structured than Rioja — black fruit and firm tannin.',
    pairs:['Roast lamb','Grilled red meat','Stews','Aged cheese'],
    prompts:['How is Ribera del Duero different from Rioja?','What is Tinto Fino?','What should I buy if I like bold Spanish reds?'] },

  // ── Argentina ───────────────────────────────────────────────────────
  'Mendoza':  { country:'Argentina', grapes:['Malbec','Cabernet Sauvignon'], keys:['mendoza'],
    taste:'High-altitude desert at the foot of the Andes. Malbec here is plush and dark-fruited with velvety tannins and a violet lift — bold but smooth.',
    pairs:['Steak','Grilled red meat','Burgers','Hard cheese'],
    prompts:['Why does Malbec grow so well in Mendoza?','What does high altitude do to the wine?','What should I buy if I like Malbec?'] },
  'Patagonia':{ country:'Argentina', grapes:['Pinot Noir','Malbec','Merlot'], keys:['patagonia','río negro','rio negro','neuquén','neuquen'],
    taste:'Argentina’s cool, windswept south. Far from Mendoza’s heat, it makes fresher, more elegant reds — perfumed Pinot Noir and lifted, high-acid Malbec.',
    pairs:['Roast chicken','Salmon','Lamb','Mushrooms'],
    prompts:['How is Patagonia different from Mendoza?','Does Argentina make good Pinot Noir?','What should I buy from Patagonia?'] },

  // ── Italy (wave 2) ──────────────────────────────────────────────────
  'Friuli':   { country:'Italy', grapes:['Friulano','Pinot Grigio','Ribolla Gialla'], keys:['friuli','collio'],
    taste:'Italy’s cool northeastern corner near Slovenia, famous for some of the country’s finest, most textural white wines — and a birthplace of skin-contact “orange” wine.',
    pairs:['Prosciutto','Seafood','Risotto','Soft cheese'],
    prompts:['What is Friulano?','What is orange wine?','What should I buy if I like Italian whites?'] },
  'Alto Adige':{ country:'Italy', grapes:['Pinot Grigio','Gewürztraminer','Schiava','Lagrein'], keys:['alto adige','südtirol','sudtirol','trentino'],
    taste:'Alpine vineyards in Italy’s far north, with a German accent. Crisp, pure, high-altitude whites (Pinot Grigio, Gewürztraminer) plus a few light, spicy local reds.',
    pairs:['Speck','Trout','Mountain cheese','Light pasta'],
    prompts:['Why are Alto Adige whites so crisp?','What is Lagrein?','What should I buy if I like Pinot Grigio?'] },
  'Campania': { country:'Italy', grapes:['Aglianico','Fiano','Greco'], keys:['campania','taurasi','fiano','greco'],
    taste:'Southern Italy around Naples, rich in ancient grapes. Aglianico (Taurasi) makes structured, age-worthy reds; Fiano and Greco give mineral, characterful whites.',
    pairs:['Pizza','Grilled meats','Seafood pasta','Aged cheese'],
    prompts:['What is Taurasi?','How is Aglianico like Nebbiolo?','What white should I try from Campania?'] },
  'Abruzzo':  { country:'Italy', grapes:['Montepulciano','Trebbiano','Pecorino'], keys:['abruzzo','montepulciano'],
    taste:'A mountainous region on Italy’s central Adriatic coast. Montepulciano d’Abruzzo gives juicy, dark, affordable reds; Pecorino and Trebbiano make fresh, easy whites.',
    pairs:['Grilled lamb','Pasta','Cured meats','Pizza'],
    prompts:['Is Montepulciano a grape or a place?','What is Pecorino wine?','What should I buy for an everyday Italian red?'] },

  // ── United States (wave 2) ──────────────────────────────────────────
  'Paso Robles':{ country:'USA', grapes:['Cabernet Sauvignon','Zinfandel','Syrah'], keys:['paso robles','paso'],
    taste:'A warm, rugged stretch of California’s Central Coast. Big, ripe, sun-soaked reds — bold Cabernet, brambly Zinfandel and Rhône-style Syrah blends.',
    pairs:['BBQ','Burgers','Grilled meats','Hard cheese'],
    prompts:['What is Paso Robles known for?','How does it compare to Napa?','What should I buy if I like bold reds?'] },
  'Columbia Valley':{ country:'USA', grapes:['Cabernet Sauvignon','Merlot','Riesling','Syrah'], keys:['washington','columbia valley','walla walla','columbia'],
    taste:'Washington State’s vast high-desert region east of the Cascades. Big day–night temperature swings give ripe-yet-firm Cabernet and Merlot, plus excellent Riesling and Syrah.',
    pairs:['Steak','Lamb','Pork','Spicy food'],
    prompts:['Why is Washington so good for Cabernet?','What is Walla Walla known for?','What should I buy if I like Bordeaux-style reds?'] },
  'Finger Lakes':{ country:'USA', grapes:['Riesling','Cabernet Franc','Chardonnay'], keys:['finger lakes','seneca','cayuga'],
    taste:'Cool, lake-tempered vineyards in upstate New York. The U.S. home of vibrant, racy Riesling — bone-dry to off-dry — plus bright, peppery Cabernet Franc.',
    pairs:['Spicy food','Pork','Trout','Soft cheese'],
    prompts:['Why is the Finger Lakes good for Riesling?','Is Finger Lakes Riesling sweet?','What should I buy if I like crisp whites?'] },

  // ── Spain (wave 2) ──────────────────────────────────────────────────
  'Priorat':  { country:'Spain', grapes:['Garnacha','Cariñena'], keys:['priorat','priorato'],
    taste:'A dramatic, slate-terraced region in Catalonia. Old-vine Garnacha and Cariñena on llicorella schist give powerful, mineral, concentrated reds — dark fruit and crushed stone.',
    pairs:['Grilled red meat','Lamb','Stews','Aged cheese'],
    prompts:['What is llicorella soil?','How is Priorat different from Rioja?','What should I buy if I like bold Spanish reds?'] },
  'Rías Baixas':{ country:'Spain', grapes:['Albariño'], keys:['rías baixas','rias baixas','albariño','albarino'],
    taste:'Spain’s rainy, green Atlantic northwest. Albariño here is crisp, saline and citrusy with a sea-breeze freshness — one of the world’s great seafood whites.',
    pairs:['Shellfish','Grilled fish','Ceviche','Fresh salads'],
    prompts:['What is Albariño like?','Why is Rías Baixas so good with seafood?','What should I buy if I like crisp whites?'] },

  // ── Portugal (wave 2) ───────────────────────────────────────────────
  'Douro':    { country:'Portugal', grapes:['Touriga Nacional','Touriga Franca','Tinta Roriz'], keys:['douro','porto','port'],
    taste:'Steep, terraced vineyards along Portugal’s Douro River — home of Port and, increasingly, bold dry reds. Dark, structured and floral, from a blend of native grapes.',
    pairs:['Grilled meats','Stews','Game','Strong cheese'],
    prompts:['What’s the difference between Port and dry Douro red?','What is Touriga Nacional?','What should I buy if I like bold reds?'] },

  // ── Germany & Austria (wave 2) ──────────────────────────────────────
  'Mosel':    { country:'Germany', grapes:['Riesling'], keys:['mosel','mosel-saar-ruwer','saar'],
    taste:'Impossibly steep slate slopes along the Mosel River. Riesling here is feather-light and low in alcohol, with electric acidity, green apple and a slatey minerality — from bone-dry to lusciously sweet.',
    pairs:['Spicy food','Pork','Trout','Thai cuisine'],
    prompts:['Is Mosel Riesling sweet or dry?','What does “Kabinett” mean?','What should I buy if I like aromatic whites?'] },
  'Rheingau': { country:'Germany', grapes:['Riesling','Spätburgunder'], keys:['rheingau'],
    taste:'A historic stretch of the Rhine making some of Germany’s most serious, structured Rieslings — riper and more powerful than the Mosel — plus elegant Spätburgunder (Pinot Noir).',
    pairs:['Pork','Roast chicken','Smoked fish','Soft cheese'],
    prompts:['How is the Rheingau different from the Mosel?','What is Spätburgunder?','What should I buy if I like dry Riesling?'] },
  'Wachau':   { country:'Austria', grapes:['Grüner Veltliner','Riesling'], keys:['wachau','austria','grüner','gruner','veltliner'],
    taste:'Terraced vineyards along the Danube — Austria’s benchmark for dry whites. Peppery, citrusy Grüner Veltliner and precise, mineral Riesling, with real depth and ageability.',
    pairs:['Schnitzel','Pork','Asparagus','Fresh herbs'],
    prompts:['What is Grüner Veltliner like?','What do Federspiel and Smaragd mean?','What should I buy if I like dry, mineral whites?'] },

  // ── Southern Hemisphere (wave 2) ────────────────────────────────────
  'Barossa Valley':{ country:'Australia', grapes:['Shiraz','Grenache','Cabernet Sauvignon'], keys:['barossa'],
    taste:'A warm valley north of Adelaide with some of the world’s oldest vines. Barossa Shiraz is rich, full-bodied and opulent — blackberry, dark chocolate and spice.',
    pairs:['BBQ','Grilled meats','Lamb','Hard cheese'],
    prompts:['Why is Barossa Shiraz so famous?','What are old-vine wines?','What should I buy if I like big reds?'] },
  'Marlborough':{ country:'New Zealand', grapes:['Sauvignon Blanc','Pinot Noir'], keys:['marlborough'],
    taste:'New Zealand’s sun-drenched, cool corner that put Kiwi Sauvignon Blanc on the map — explosively aromatic, zesty and tropical, with a grassy, passionfruit punch.',
    pairs:['Goat cheese','Shellfish','Salads','Asian food'],
    prompts:['Why does Marlborough Sauvignon taste so distinctive?','Does Marlborough make good Pinot Noir?','What should I buy if I like zesty whites?'] },
  'Central Otago':{ country:'New Zealand', grapes:['Pinot Noir'], keys:['central otago','otago'],
    taste:'The world’s southernmost wine region, in New Zealand’s mountainous interior. Intense sunlight and cold nights give vivid, perfumed Pinot Noir — dark cherry, wild thyme and silky depth.',
    pairs:['Duck','Lamb','Salmon','Mushrooms'],
    prompts:['Why is Central Otago good for Pinot Noir?','How does it compare to Burgundy?','What should I buy if I like bold Pinot?'] },
};
