// regions.js — curated Explore region library (first wave, ~22 regions).
// Each region: { country, grapes[], keys[] (search aliases + own-from-here match),
//   taste, pairs[], prompts[3] (region-specific sommelier conversation starters) }.
// FEATURED = the default pills shown when the search box is empty.

export const FEATURED = ['Beaujolais','Burgundy','Loire','Piedmont','Tuscany','Napa Valley','Oregon','Mendoza'];

export const REGIONS = {
  // ── France ──────────────────────────────────────────────────────────
  'Beaujolais':{ country:'France', grapes:['Gamay'], keys:['beaujolais','morgon','fleurie','brouilly'],
    taste:'Granite hills just south of Burgundy. Gamay here is juicy, floral and low-tannin — joyful, chillable reds that go with almost anything.',
    pairs:['Charcuterie','Roast chicken','Picnic spreads','Thanksgiving dinner'],
    prompts:['Is Gamay the only grape grown in Beaujolais?','What is a Cru Beaujolais?','What should I buy next if I like Beaujolais?'] },
  'Burgundy': { country:'France', grapes:['Pinot Noir','Chardonnay'], keys:['burgundy','bourgogne','côte'],
    taste:'The world’s benchmark for Pinot Noir and Chardonnay. Precise, earthy, and age-worthy — wines that trade power for detail and a sense of place.',
    pairs:['Roast chicken','Mushrooms','Soft cheese','Salmon'],
    prompts:['Why is Burgundy so expensive?','What’s the difference between a Village and a Premier Cru?','Where should I look for affordable Burgundy?'] },
  'Chablis':  { country:'France', grapes:['Chardonnay'], keys:['chablis'],
    taste:'Burgundy’s coolest, northernmost outpost. Chardonnay here is bone-dry, steely and mineral — green apple and crushed-shell, with little or no oak. Precision in a glass.',
    pairs:['Oysters','Shellfish','Goat cheese','Sushi'],
    prompts:['What makes Chablis taste so different from other Chardonnay?','What is Kimmeridgian soil?','What should I buy if I like Chablis?'] },
  'Champagne':{ country:'France', grapes:['Chardonnay','Pinot Noir','Pinot Meunier'], keys:['champagne'],
    taste:'The benchmark for sparkling wine, from chalky soils northeast of Paris. Bracing acidity, fine bubbles, and flavours of green apple, brioche and toasted nuts.',
    pairs:['Oysters','Fried foods','Soft cheese','Celebrations'],
    prompts:['What does “Brut” actually mean?','What is Blanc de Blancs?','Is grower Champagne worth seeking out?'] },
  'Loire':    { country:'France', grapes:['Chenin Blanc','Sauvignon Blanc','Cabernet Franc','Melon de Bourgogne'], keys:['loire','montlouis','vouvray','sancerre','muscadet'],
    taste:'A long, cool river valley making some of France’s most refreshing wines — crisp, mineral whites (Chenin, Sauvignon) and bright, leafy reds (Cabernet Franc).',
    pairs:['Goat cheese','Shellfish','Pork','Fresh salads'],
    prompts:['What grapes is the Loire known for?','What exactly is Sancerre?','What’s a good Loire wine for oysters?'] },
  'Rhône':    { country:'France', grapes:['Syrah','Grenache','Mourvèdre','Viognier'], keys:['rhone','rhône','châteauneuf','chateauneuf','hermitage','côte-rôtie','gigondas'],
    taste:'A sun-warmed valley in two halves: peppery, smoky Syrah in the north; generous Grenache-led blends in the south (Châteauneuf-du-Pape). Warm, savoury, herb-and-spice reds.',
    pairs:['Grilled meats','Lamb','Stews','Hard cheese'],
    prompts:['What’s the difference between Northern and Southern Rhône?','What grapes go into Châteauneuf-du-Pape?','What should I buy if I like Syrah?'] },
  'Bordeaux': { country:'France', grapes:['Cabernet Sauvignon','Merlot','Cabernet Franc'], keys:['bordeaux','médoc','medoc','margaux','pomerol','saint-émilion','st-émilion'],
    taste:'The world’s most famous red region. The Left Bank is Cabernet-driven and structured; the Right Bank is plush and Merlot-led. Cassis, cedar, tobacco and firm, age-worthy tannin.',
    pairs:['Steak','Lamb','Roast beef','Aged cheese'],
    prompts:['What’s the difference between Left Bank and Right Bank?','Why is Bordeaux usually a blend?','How do I find good affordable Bordeaux?'] },
  'Alsace':   { country:'France', grapes:['Riesling','Gewürztraminer','Pinot Gris'], keys:['alsace'],
    taste:'A sunny, German-influenced corner of eastern France. Aromatic, mostly dry whites — racy Riesling, exotic Gewürztraminer — with purity, perfume and a floral lift.',
    pairs:['Spicy food','Pork','Charcuterie','Onion tart'],
    prompts:['Is Alsace Riesling sweet or dry?','What is Gewürztraminer like?','What pairs well with Alsace whites?'] },

  // ── Italy ───────────────────────────────────────────────────────────
  'Piedmont': { country:'Italy', grapes:['Nebbiolo','Barbera','Dolcetto'], keys:['piedmont','piemonte','barolo','barbaresco'],
    taste:'Foggy hills in Italy’s northwest. Nebbiolo (Barolo, Barbaresco) is pale but powerful — tar, roses, and firm tannin that rewards patience.',
    pairs:['Braised beef','Mushroom risotto','Truffle dishes','Aged cheese'],
    prompts:['What’s the difference between Barolo and Barbaresco?','Why does Nebbiolo need aging?','What should I buy if I like Piedmont reds?'] },
  'Tuscany':  { country:'Italy', grapes:['Sangiovese'], keys:['tuscany','toscana','chianti','montepulciano','brunello'],
    taste:'Sun-baked hills of central Italy. Sangiovese gives tart-cherry fruit, dried herbs, and a savory, mouth-watering grip — built for the table (Chianti, Brunello).',
    pairs:['Pizza','Pasta with red sauce','Cured meats','Grilled vegetables'],
    prompts:['What’s the difference between Chianti and Brunello?','What is a Super Tuscan?','What food pairs best with Sangiovese?'] },
  'Veneto':   { country:'Italy', grapes:['Corvina','Glera','Garganega'], keys:['veneto','valpolicella','amarone','soave','prosecco'],
    taste:'Italy’s prolific northeast — fizzy Prosecco, crisp Soave whites, and rich, raisined Amarone made from dried Corvina grapes. The range runs from breezy to brooding.',
    pairs:['Antipasti','Risotto','Braised meats','Hard cheese'],
    prompts:['What is Amarone and why is it special?','Is all Prosecco sweet?','What should I buy if I like Italian reds?'] },
  'Sicily':   { country:'Italy', grapes:['Nero d’Avola','Grillo','Frappato'], keys:['sicily','sicilia'],
    taste:'A sun-baked Mediterranean island making bold, juicy reds from Nero d’Avola and fresh, saline whites from Grillo. Generous fruit with a wild, herbal edge.',
    pairs:['Grilled fish','Pasta','Eggplant','Cured meats'],
    prompts:['What is Nero d’Avola like?','What white wines does Sicily make?','What should I try from Sicily?'] },
  'Etna':     { country:'Italy', grapes:['Nerello Mascalese','Carricante'], keys:['etna'],
    taste:'Volcanic vineyards on the slopes of Mount Etna. Nerello Mascalese gives pale, high-acid, almost Burgundian reds — ash, red cherry and smoke — grown on black volcanic soils.',
    pairs:['Roast chicken','Mushrooms','Grilled fish','Tomato pasta'],
    prompts:['Why is Etna compared to Burgundy?','What does volcanic soil do to wine?','What should I buy if I like Nerello Mascalese?'] },

  // ── United States ───────────────────────────────────────────────────
  'Napa Valley':{ country:'USA', grapes:['Cabernet Sauvignon','Chardonnay','Merlot'], keys:['napa','oakville','rutherford','stags leap'],
    taste:'California’s most famous valley. Warm days and cool nights give rich, ripe Cabernet Sauvignon — bold black fruit, polished tannin, and generous oak.',
    pairs:['Ribeye','Lamb','Burgers','Aged hard cheese'],
    prompts:['Why is Napa Cabernet so prized?','What’s the difference between Napa and Sonoma?','What should I buy if I like Napa Cabernet?'] },
  'Sonoma':   { country:'USA', grapes:['Pinot Noir','Chardonnay','Zinfandel'], keys:['sonoma','russian river','dry creek'],
    taste:'Napa’s cooler, more laid-back neighbour. Coastal fog brings elegant Pinot Noir and Chardonnay (Russian River) plus old-vine Zinfandel — a little fresher and more varied than Napa.',
    pairs:['Salmon','Roast chicken','Pork','Mushrooms'],
    prompts:['What’s the difference between Napa and Sonoma?','What is Russian River Valley known for?','What should I buy if I like Sonoma Pinot?'] },
  'Oregon':   { country:'USA', grapes:['Pinot Noir','Chardonnay','Pinot Gris'], keys:['oregon'],
    taste:'Cool, rainy and green — Oregon makes high-acid Pinot Noir full of red-cherry fruit, freshness, and an earthy, forest-floor edge. Think elegance over power.',
    pairs:['Roast chicken','Salmon','Mushroom dishes','Duck'],
    prompts:['Why is Oregon known for Pinot Noir?','What is the Willamette Valley?','How does Oregon Pinot differ from Burgundy?'] },
  'Willamette Valley':{ country:'USA', grapes:['Pinot Noir','Chardonnay','Pinot Gris'], keys:['willamette'],
    taste:'Oregon’s cool, green heart and one of the world’s great Pinot Noir zones. Red-cherry fruit, bright acidity and an earthy, forest-floor depth — elegance over power.',
    pairs:['Salmon','Duck','Mushrooms','Roast chicken'],
    prompts:['Why is the Willamette Valley so good for Pinot Noir?','How does it compare to Burgundy?','What should I buy if I like Oregon Pinot?'] },
  'Santa Barbara':{ country:'USA', grapes:['Pinot Noir','Chardonnay','Syrah'], keys:['santa barbara','sta. rita','santa rita','sta rita','santa ynez'],
    taste:'Central-coast California where east–west valleys funnel cool ocean air inland. Bright Pinot Noir and Chardonnay (Sta. Rita Hills) plus peppery, cool-climate Syrah.',
    pairs:['Grilled fish','Roast chicken','Pork','Mushrooms'],
    prompts:['What is Sta. Rita Hills known for?','Why is Santa Barbara good for Pinot Noir?','What should I buy from Santa Barbara?'] },

  // ── Spain ───────────────────────────────────────────────────────────
  'Rioja':    { country:'Spain', grapes:['Tempranillo','Garnacha'], keys:['rioja'],
    taste:'Spain’s classic red region. Tempranillo aged in American oak gives savoury red fruit, leather, dill and vanilla. Crianza, Reserva and Gran Reserva mark increasing age.',
    pairs:['Lamb','Grilled meats','Cured meats','Hard cheese'],
    prompts:['What do Crianza, Reserva and Gran Reserva mean?','What grape is Rioja made from?','What should I buy if I like Rioja?'] },
  'Ribera del Duero':{ country:'Spain', grapes:['Tempranillo'], keys:['ribera','duero'],
    taste:'A high, harsh plateau north of Madrid making powerful Tempranillo (here called Tinto Fino). Darker, denser and more structured than Rioja — black fruit and firm tannin.',
    pairs:['Roast lamb','Grilled red meat','Stews','Aged cheese'],
    prompts:['How is Ribera del Duero different from Rioja?','What is Tinto Fino?','What should I buy if I like bold Spanish reds?'] },

  // ── Argentina ───────────────────────────────────────────────────────
  'Mendoza':  { country:'Argentina', grapes:['Malbec','Cabernet Sauvignon'], keys:['mendoza'],
    taste:'High-altitude desert at the foot of the Andes. Malbec here is plush and dark-fruited with velvety tannins and a violet lift — bold but smooth.',
    pairs:['Steak','Grilled red meat','Burgers','Hard cheese'],
    prompts:['Why does Malbec grow so well in Mendoza?','What does high altitude do to the wine?','What should I buy if I like Malbec?'] },
  'Patagonia':{ country:'Argentina', grapes:['Pinot Noir','Malbec','Merlot'], keys:['patagonia','río negro','rio negro','neuquén','neuquen'],
    taste:'Argentina’s cool, windswept south. Far from Mendoza’s heat, it makes fresher, more elegant reds — perfumed Pinot Noir and lifted, high-acid Malbec.',
    pairs:['Roast chicken','Salmon','Lamb','Mushrooms'],
    prompts:['How is Patagonia different from Mendoza?','Does Argentina make good Pinot Noir?','What should I buy from Patagonia?'] },
};
