import { T } from '../lib/data.js';
import { V_STATUS } from '../lib/constants.js';
import { Icon } from './ui.jsx';
import { Hamburger } from './home.jsx';
const foods=[['●','Steak'],['▲','Pizza'],['◖','Seafood'],['●','Chicken'],['◢','Cheese'],['●','Spicy'],['◒','Vegetables'],['♠','Mushroom'],['◡','Pasta']];
const glasses=[['Red','#9b2f3a'],['White','#b58a17'],['Rosé','#d07a8a'],['Sparkling','#caa023']];
function PairingHome({onBack,onMenu,onAsk}){return <div style={{position:'absolute',inset:0,zIndex:80,background:'#fff',overflowY:'auto'}}><div style={{paddingTop:V_STATUS}}/>
  <header style={{height:56,display:'grid',gridTemplateColumns:'46px 42px 1fr 88px',alignItems:'center',borderBottom:`1px solid ${T.line}`,padding:'0 14px'}}><Hamburger onClick={onMenu}/><button aria-label="Back" onClick={onBack} style={{border:0,background:'none',padding:8,cursor:'pointer'}}><Icon name="back" size={21} color={T.ink}/></button><div style={{fontFamily:'var(--serif)',fontSize:20,textAlign:'center'}}>Pairings</div><div/></header>
  <main style={{padding:'8px 16px 36px'}}><button onClick={()=>onAsk('')} style={{width:'100%',height:53,border:`1px solid ${T.line2}`,borderRadius:13,background:T.raised,display:'flex',alignItems:'center',gap:12,padding:'0 15px',cursor:'pointer'}}><Icon name="sparkle" size={16} color={T.maybe}/><span style={{fontSize:15.5,color:T.ink3}}>Ask your sommelier…</span></button>
  <div style={{borderTop:`1px solid ${T.line}`,margin:'14px -16px 0',padding:'20px 16px 0'}}><div style={{fontSize:11,letterSpacing:'.04em',color:T.ink3,textTransform:'uppercase'}}>What are you eating?</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:9,marginTop:13}}>{foods.map(([glyph,label])=><button key={label} onClick={()=>onAsk(`What wine pairs with ${label.toLowerCase()}?`)} style={{height:92,border:`1px solid ${T.line2}`,borderRadius:14,background:'#fff',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:10,cursor:'pointer',fontSize:13,fontWeight:650,color:T.ink}}><span aria-hidden="true" style={{fontSize:22,lineHeight:1}}>{glyph}</span>{label}</button>)}</div></div>
  <div style={{fontSize:11,letterSpacing:'.04em',color:T.ink3,textTransform:'uppercase',marginTop:25}}>Or start with a glass</div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:8,marginTop:13}}>{glasses.map(([label,color])=><button key={label} onClick={()=>onAsk(`What food pairs with ${label.toLowerCase()} wine?`)} style={{height:84,border:`1px solid ${T.line2}`,borderRadius:14,background:'#fff',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:7,cursor:'pointer',fontSize:12,fontWeight:650,color:T.ink}}><Icon name="glass" size={25} color={color} stroke={2}/>{label}</button>)}</div>
  <p style={{display:'flex',gap:10,margin:'25px 2px 0',fontSize:12.5,lineHeight:1.55,color:T.ink4}}><Icon name="sparkle" size={12} color={T.ink4} style={{flexShrink:0,marginTop:3}}/>Or type any question above — each answer explains the style and region, then shows the bottles you already own that fit.</p></main></div>}
export { PairingHome };
